# Generated by Django 5.0.1 on 2024-03-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(default=None, max_length=20, verbose_name='Электронная почта'),
        ),
    ]
